version: "3.2"

services:
  gitea:
    image: pistacks/gitea:1.10.0
    ports:
      - 2222:2222
    volumes:
      - vol_gitea:/data
    environment:
      - APP_NAME=gitea.${DOMAIN:-localhost}
      - USER_UID=1000
      - USER_GID=1000
      - ROOT_URL=http://gitea.${DOMAIN:-localhost}
      - SSH_DOMAIN=gitea.${DOMAIN:-localhost}
      - SSH_PORT=2222
      - HTTP_PORT=3000
      - DB_TYPE=sqlite3
    deploy:
      labels:
        - traefik.port=3000
        - traefik.backend=gitea
        - traefik.frontend.rule=Host:gitea.${DOMAIN:-localhost}
        - traefik.docker.network=traefik
    networks:
      - traefik
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

  drone-server:
    image: pistacks/drone-server:1.2.3
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - vol_drone:/var/lib/drone
    environment:
      - DRONE_DEBUG=true
      - DRONE_ADMIN=rbekker87
      - DRONE_USER_CREATE=username:rbekker87,admin:true
      - DRONE_SERVER_PORT=:80
      - DRONE_DATABASE_DRIVER=sqlite3
      - DRONE_GIT_ALWAYS_AUTH=false
      - DRONE_GITEA_SERVER=http://gitea:3000
      - DRONE_RPC_SECRET=${DRONE_SECRET}
      - DRONE_SERVER_HOST=drone-server:80
      - DRONE_HOST=http://drone-server:80
      - DRONE_SERVER_PROTO=http
      - DRONE_TLS_AUTOCERT=false
      - DRONE_AGENTS_ENABLED=true
      - DRONE_DATABASE_DATASOURCE=/database.sqlite
    deploy:
      labels:
        - traefik.port=80
        - traefik.backend=drone-server
        - traefik.frontend.rule=Host:drone.${DOMAIN:-localhost}
        - traefik.docker.network=traefik
    networks:
      - traefik
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

  drone-agent:
    image: pistacks/drone-agent:1.2.3
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DRONE_RPC_SERVER=http://drone-server:80
      - DRONE_RPC_SECRET=${DRONE_SECRET}
      - DRONE_RUNNER_CAPACITY=2
      - DRONE_AGENT="${HOSTNAME}"
      - DOCKER_OS=linux
      - DOCKER_ARCH=arm
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
           - node.role==manager
    networks:
      - traefik
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

networks:
  traefik:
    external: true

volumes:
  vol_gitea:
    driver: local
    driver_opts:
      type: nfs
      o: addr=${NFS_SERVER_IP},nolock,soft,rw
      device: ":/opt/nfs/volumes/gitea"

  vol_drone:
    driver: local
    driver_opts:
      type: nfs
      o: addr=${NFS_SERVER_IP},nolock,soft,rw
      device: ":/opt/nfs/volumes/drone"
