global:
  scrape_interval:     15s
  evaluation_interval: 15s
  external_labels:
      monitor: 'pistack-monitor'

rule_files:
  - 'alert.rules'

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 15s
    static_configs:
      - targets: ['prometheus:9090']

#  - job_name: 'ext-node'
#    scrape_interval: 15s
#    static_configs:
#      - targets: ['192.168.0.2:9100']

  - job_name: 'node'
    scrape_interval: 15s
    dns_sd_configs:
      - names:
        - 'tasks.node-exporter'
        type: 'A'
        port: 9100

  - job_name: 'cadvisor'
    scrape_interval: 15s
    dns_sd_configs:
    - names:
      - 'tasks.cadvisor'
      type: 'A'
      port: 8080

  - job_name: 'traefik-exporter'
    dns_sd_configs:
    - names:
      - 'tasks.traefik'
      type: 'A'
      port: 8080

  - job_name: 'pushgateway'
    scrape_interval: 15s
    dns_sd_configs:
    - names:
      - 'tasks.pushgateway'
      type: 'A'
      port: 9091

  - job_name: 'arm-exporter'
    scrape_interval: 15s
    dns_sd_configs:
      - names:
        - 'tasks.arm-exporter'
        type: 'A'
        port: 9243
